version: '3'
services:
  # Servicio de Node.js
  node_app:
    build: .
    container_name: sinapsis_app
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/app/dist
    depends_on:
      - mysql
    networks:
      - my_network
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    restart: always

  # Servicio de MySQL
  mysql:
    build: ./mysql
    container_name: sinapsis_mysql
    restart: always
    ports:
      - ${HOST_MACHINE_MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - my_network

networks:
  my_network:
  